[tool.poetry]
name = "ssz"
version = "0.1.0"
description = "Visualize different dimensions in SSZ datasets"
authors = ["Magdalena Surówka"]

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.1.3"
geojson = "^2.5.0"
geomet = "^0.2.1"
matplotlib = "^3.3.2"
plotly = "^4.11.0"
ipykernel = "^5.3.4"
sparqlkernel ="^1.3.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
